### ISSUE TITLE
The app can not use

### ISSUE THREAD

**Issue by zwb124** [ntfstool/ntfstool#1]
Thank you for developing the software, I inserted my ntfs mobile hard drive and the app can't mount

**Comment by ntfstool** [comment]
Yes, it is currently found that it cannot be mounted on some versions of the MAC OS system, we are working on a solution, thank you for using it.


Alphone

**Comment by ZZZZone** [comment]
Always prompt for administrator password, still prompt for correct administrator password

**Comment by ntfstool** [comment]
The latest 2.0.1 version has solved this problem, welcome to download the experience.
