### ISSUE TITLE
Always prompt for administrator password

### ISSUE THREAD

**Issue by ZZZZone** [ntfstool/ntfstool#2]
Always prompt for administrator password, still prompt for correct administrator password
And the NTFS still read only
MacOS 10.15.2

**Comment by 852208555** [comment]
We are very sorry for this problem. Now about 1. administrator rights prompt box bug 2. Mount read-only problem and other discovered problems, we are hurrying to fix and develop.
please pay attention to our subsequent updates, thanks.

**Comment by vsnotme** [comment]
遇到了与ZZZZone相同的问题，10.15.4

**Comment by Sanbolee** [comment]
遇到了与ZZZZone相同的问题，10.15.3

**Comment by zengtengcq** [comment]
same issue.

**Comment by likunyan** [comment]
me too

**Comment by maywzh** [comment]
Same issue in 10.15.4

**Comment by yxwoaiy** [comment]
me to 10.15.4

**Comment by HankBu** [comment]
一样的 一直叫我输入密码 不能用哈

**Comment by charzone95** [comment]
still happen to me in latest release (2.3.2)
MacOS Catalina 10.15.4 (19E287)
