### ISSUE TITLE
如何卸载该软件

### ISSUE THREAD

**Issue by alakenda** [ntfstool/ntfstool#40]
整个网站上只说了怎么装，怎么用，怎么没说怎么卸载啊？

**Comment by XuCpeng** [comment]
> 整个网站上只说了怎么装，怎么用，怎么没说怎么卸载啊？

这还用说吗... 这就是一个普通的app而已，卸载的方式都是通用的。

如果你确实需要一个卸载工具，你可以使用同样简洁免费的AppCleaner进行卸载：[Appcleaner](http://freemacsoft.net/appcleaner/) （仅提供建议）

（如果你的问题解决了，请close issues）

**Comment by alakenda** [comment]
> > 整个网站上只说了怎么装，怎么用，怎么没说怎么卸载啊？
> 
> 这还用说吗... 这就是一个普通的app而已，卸载的方式都是通用的。
> 
> 如果你确实需要一个卸载工具，你可以使用同样简洁免费的AppCleaner进行卸载：[Appcleaner](http://freemacsoft.net/appcleaner/) （仅提供建议）
> 
> （如果你的问题解决了，请close issues）

感谢，试了一下，感觉确实没留下什么垃圾
