### ISSUE TITLE
Hardcoded strings

### ISSUE THREAD

**Issue by cheack** [ntfstool/ntfstool#5]
Hi, I've started translating you program to Russian language and I've faced with some hardcoded strings, which cannot be translated.
Some examples: 
https://github.com/ntfstool/ntfstool/blob/master/src/main/lib/PageConfig.js#L419
https://github.com/ntfstool/ntfstool/blob/master/src/renderer/page/FeedBack.vue#L22
https://github.com/ntfstool/ntfstool/blob/master/src/renderer/page/Home.vue#L68

Please add the language strings for them and then I will be able to complete the translation.
Or, I can create a PR, but I'm not sure how to add the strings for Chinese, Japanese and the other languages - I simply don’t know them :) Of course, I can use Google Translate, but then I can’t guarantee the correct translation.

**Comment by ntfstool** [comment]
Ok, I have merged the requests and updated the corresponding strings, thank you for your support and efforts.
