### ISSUE TITLE
m2pro 设置了还是显示只读模式要安装驱动

### ISSUE THREAD

**Issue by huqi777** [ntfstool/ntfstool#78]
版本14.0 (23A344)，按教程终端输入了csrutil disable ，并且启动了，然后勾选 降低安全性 和他下面的两个复选框，然后重启，但是设置里面安全性没有提示可以勾选的，软件里面移动硬盘也显示只读模式要安装驱动
![WX20240304-094937@2x](https://github.com/ntfstool/ntfstool/assets/81685816/5f59d504-8d67-4027-9a2c-ff7bc1142092)

**Comment by huqi777** [comment]
设置里面也没有detail相关选项
![WX20240304-095130@2x](https://github.com/ntfstool/ntfstool/assets/81685816/51129ed9-63fe-4e63-8e64-0a32ef746f66)

**Comment by ntfstool** [comment]
需要点击左下角 "安装" 驱动按钮,直到安装完成才行.

安装过程中需要重启电脑到恢复模式,并完成下列两项操作:
1) 禁用系统完整性保护(SIP)
2) 开启'允许用户管理来自被认可开发者的内核扩展'选项

**Comment by BYNepenthe** [comment]
M3 还是不行
版本用的是 3.5.1
