### ISSUE TITLE
Please support Homebrew

### ISSUE THREAD

**Issue by MarcusPierce** [ntfstool/ntfstool#9]
Please support Homebrew

**Comment by ntfstool** [comment]
Okay, we will join in in the future

**Comment by fangzhengjin** [comment]
https://github.com/Homebrew/homebrew-cask/pull/82129

**Comment by fangzhengjin** [comment]
@ntfstool  ntfstool can already be found in the Homebrew, I think this issue can be closed ~

**Comment by ntfstool** [comment]
Thank you for your submission and support 👍
